# Assembly output for: ../test/fixtures/simple.c
# Generated by YAC Compiler v0.5.0
# Optimization level: -O2

	.text
	.intel_syntax noprefix

	.globl _main
_main:
	push rbp
	mov rbp, rsp
	sub rsp, 128
	mov rax, 42
	mov rsp, rbp
	pop rbp
	ret

